name: cncra
version: '1.0'
summary: C&C Red Alert is a real-time strategy game.
description: |
 Command & Conquer: Red Alert is a real-time strategy game and second release in the Command & Conquer series, having been released in October of 1996. it is also the first game in the Red Alert sub-series that takes an alternative path/story of the main Command & Conquer series.

 C&C: Red Alert is set prior to the events in Command & Conquer in an alternative history where the Soviet Union has invaded Eastern Europe and started a new war against the remaining European countries and the United States.

 When the game was released in 1996 it was praised by fans and critics alike for its intuitive user interface and gameplay that was ahead of its time. New, groundbreaking features introduced with the release of Command & Conquer Red Alert included the ability to queue commands, create and assign multiple units into a single group by a simple drag and select, as well as multiple factions with different strengths and weaknesses. These features have since become standard for the genre.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform

apps:
  cncra:
    command: |
      bin/sommelier "$(find $WINEPREFIX/ -type f \( -name 'RA1MPLauncher.exe' -o -name 'RA95Launcher.exe' \) 2>/dev/null)"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
      INSTALL_URL_RA: "https://downloads.cncnet.org/RA1installer.exe" # cncra full game setup
      INSTALL_URL_CNC: "https://downloads.cncnet.org/RedAlert1_Online_Installer.exe" # cncra multiplayer only setup
      MONO_URL: "https://dl.winehq.org/wine/wine-mono/4.7.1/wine-mono-4.7.1.msi"
      TRICKS: "dotnet20"
      VIRTDESKTOP: 0
      LC_ALL: "C.UTF-8"
    plugs:
      - wine-platform-plug
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio
      - wayland
      - x11
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-platform/bin/winetricks prefix="$WINEPREFIX"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=;winemenubuilder.exe=d" # Prevent pop-ups about Wine Gecko
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - wayland
      - x11

parts:
  cncra:
    plugin: dump
    source: scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'sommelier': bin/